PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?t (AVG(?count_preds) AS ?avg_width) {
  SELECT ?p (COUNT (DISTINCT ?p) AS ?count_preds) {
    ?s ?p ?o .
    ?s rdf:type ?t .
  }
  GROUP BY ?s
}
GROUP BY ?t
ORDER BY ?avg_width

  SELECT ?p (COUNT (DISTINCT ?p) AS ?count_preds) {
    ?s ?p ?o .
  }
  GROUP BY ?p
  ORDER BY ?cound_preds
