PREFIX film: <http://cambridgesemantics.com/ontologies/2009/08/Film#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?cls1 ?p1 ?cls2 ?p2 (LOG(COUNT(?o1), 2) AS ?max_ent)
WHERE {
  ?s ?p1 ?o1 .
  ?s ?p2 ?o2 .
  ?s a ?cls1 .
  ?s a ?cls2 .
}
GROUP BY ?cls1 ?p1 ?cls2 ?p2
ORDER BY ?cls1 ?p1 ?cls2 ?p2
VALUES (?cls1 ?p1 ?cls2 ?p2) {
  %s
}
